apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example-namespace
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 2
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
           

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: example-app
  name: example-app
  namespace: example-namespace
spec:
  ports:
  - port: 80
  selector:
    app: example-app    
